export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_NEXT_PAGE_REQUEST = "FETCH_NEXT_PAGE_REQUEST";
export const FETCH_NEXT_PAGE_SUCCESS = "FETCH_NEXT_PAGE_SUCCESS";
